### ISSUE TITLE
[next] type arguments for views at instantiation time

### ISSUE THREAD

**Issue by sh-dave** [PDeveloper/eskimo#9]
**https://github.com/sh-dave/eskimo-issues/tree/master/view-arguments-instantiation**

With haxe's maps i can do:

``` haxe
class S1 extends System {
      var v : View<C>;
      var m : Map<Int, C>;

      override public function onStart( sm : SystemManager ) {
            m = new Map(); // no <Int, C> neccessary
      }
}
```

This doesn't work for views. I have to type the type arguments again

``` haxe
      override public function onStart( sm : SystemManager ) {
           v = new View<C>(sm.entities); // <C> neccessary
      }
```

**Comment by PDeveloper** [comment]
For easier View creation I'll be adding some tools to reduce boiler-plate.
But I'll see if I can fix this to make things easier. Under the hood, a new type gets built that isn't even generic, which is why this might be the case.

(I found that inlining doesn't work properly with generic types, but if this gets fixed, I'll be able to revert to using generics and have this work as expected I think)

**Comment by sh-dave** [comment]
Ok no sweat, this is only a minor issue (at least for me). I use code like this now instead:

``` haxe
class S1 extends System {
      var v = new View<C>();

      override public function onStart( sm : SystemManager ) {
          v.initialize(sm.entities);
      }
}
```
